/**
 * SSE
 * Web service
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProofPathDTO { 
    id: number;
    timestamp: number;
    event: string;
    user_id: string;
    user_token: string;
    rep_id: number;
    goal_id: number;
}