/**
 * SSE
 * Web service
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProofRepForDAGDTO { 
    user_token: string;
    rep_id: number;
}